default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] || "localhost" %>
  username: <%= ENV["DB_USER"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] || "postgres" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>

test:
  <<: *default
  database: <%= ENV["DB_NAME"] %>

production:
  <<: *default
  database:  <%= ENV["DB_NAME"] %>
